version: '3'
services:
  nginx:
    image: nginx:1.10
    container_name: api-nginx
    links:
      - php-fpm
      - php-cli
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - php-cli

  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    container_name: aoi-php-fpm
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    container_name: api-php-cli
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql-api
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3306:$DB_PORT"
    env_file:
      - .env
    environment:
      - "MYSQL_ROOT_PASSWORD=$DB_PASSWORD"
      - "MYSQL_USER=$DB_USERNAME"
      - "MYSQL_PASSWORD=$DB_PASSWORD"
      - "MYSQL_DATABASE=$DB_DATABASE"
  node:
    container_name: api-node
    image: node:8.6-alpine
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true
